### ISSUE TITLE
Question/Discussion: Is is it not better to use docker compose for updating the services?

### ISSUE THREAD

**Issue by qubusp** [decayofmind/ansible-bluegreen-docker#3]
Hi Roman, 

I came across the `docker_service` - module in Ansible, which is basically about docker compose. Would it not simplify/easify the concept aka make the transition more seamless? If you split the machines in the inventory in two groups general groups `green` and `blue`? 

If we theoretically would speak about and inventory that would be in yaml format:

```
bg_blue:
        hosts:
           10.0.0.1
           10.0.0.3
        vars:
           blue: true

bg_green:
         hosts:
           10.0.0.2
           10.0.0.4
         vars:
             green: true
```

And move on from there?

**Comment by decayofmind** [comment]
Hi,
purpose of the role is to keep `green` and `blue` set of containers on the same machine, so splitting in inventory would be meaningless.

Speaking about `docker_service`, it can be used, but not sure about benefits.

**Comment by qubusp** [comment]
Hi, 
the benefit I see from `docker-compose` is the scaling mechanism. The logic in the role is perfect and I highly admire it. For the purposes of deployment with compose I think that `app_version` should be included in the service name. The only thing I believe has to be rewritten is the application of the compose file, for which you already have the vars in defaults. I will make a pull request later today.
